apiVersion: v1
data:
  DOCKER_PASSWORD: YWNjZXNzLXRva2Vu
  DOCKER_USERNAME: c2VyYW5pc2U=
  EUREKA_HOST: ZGlzY292ZXJ5LXNlcnZlcg==
  EUREKA_PASSWORD: eW91cl9ldXJla2FfcGFzc3dvcmRfaGVyZQ==
  EUREKA_PORT: ODc2MQ==
  EUREKA_USERNAME: ZXVyZWth
  GF_SECURITY_ADMIN_PASSWORD: cGFzc3dvcmQ=
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  KAFKA_HOST: a2Fma2EtYnJva2VyLTE=
  KAFKA_PORT_EXTERNAL: OTA5Mg==
  KAFKA_PORT_INTERNAL: MTkwOTI=
  POSTGRES_DONOR_DB: ZG9ub3Jfc2VydmljZQ==
  POSTGRES_DONOR_PASS: ZG9ub3JfcGFzcw==
  POSTGRES_DONOR_PORT: NTQzNA==
  POSTGRES_DONOR_USER: ZG9ub3JfdXNlcg==
  POSTGRES_IDENTITY_DB: aWRlbnRpdHlfc2VydmljZQ==
  POSTGRES_IDENTITY_PASS: aWRlbnRpdHlfcGFzcw==
  POSTGRES_IDENTITY_PORT: NTQzNQ==
  POSTGRES_IDENTITY_USER: aWRlbnRpdHlfdXNlcg==
  POSTGRES_LABORATORY_DB: bGFib3JhdG9yeV9zZXJ2aWNl
  POSTGRES_LABORATORY_PASS: bGFib3JhdG9yeV9wYXNz
  POSTGRES_LABORATORY_PORT: NTQ0MQ==
  POSTGRES_LABORATORY_USER: bGFib3JhdG9yeV91c2Vy
  POSTGRES_MEETING_DB: bWVldGluZ19zZXJ2aWNl
  POSTGRES_MEETING_PASS: bWVldGluZ19wYXNz
  POSTGRES_MEETING_PORT: NTQzOQ==
  POSTGRES_MEETING_USER: bWVldGluZ191c2Vy
  POSTGRES_NOTIFICATION_DB: bm90aWZpY2F0aW9uX3NlcnZpY2U=
  POSTGRES_NOTIFICATION_PASS: bm90aWZpY2F0aW9uX3Bhc3M=
  POSTGRES_NOTIFICATION_PORT: NTQ0MA==
  POSTGRES_NOTIFICATION_USER: bm90aWZpY2F0aW9uX3VzZXI=
  POSTGRES_ZONE_DB: em9uZV9zZXJ2aWNl
  POSTGRES_ZONE_PASS: em9uZV9wYXNz
  POSTGRES_ZONE_PORT: NTQzNg==
  POSTGRES_ZONE_USER: em9uZV91c2Vy
  SMS_PASSWORD: TW1FME16QTJOVFUzWTJWaU5XUXdaRFF4WkRZMFpqSXpPVGs1TnpZd1lUZGpNV0ZpTkRVME9XRTFNekJpTmprM1pEa3hZMkZtWW1Sa05XWm1PVGswTkE9PQ==
  SMS_SOURCE: VVNDSEU=
  SMS_URL: aHR0cHM6Ly9hcGlzbXMuYmVlbS5hZnJpY2EvdjEvc2VuZA==
  SMS_USERNAME: MTkzZjE2YzVjZmY3N2JjYg==
  ZOOKEEPER_PORT: MjE4MQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: app-secrets
